
name: geocontrol_sql

services:
  geocontrol_sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: geocontrol_sql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SQL_PASSWORD}
      - MSSQL_PID=Express
      - TZ=America/Bogota
    ports:
      - "1433:1433"
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "${SQL_PASSWORD}" -C -Q "SELECT 'Healthcheck OK'"
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 15s
    restart: unless-stopped
    networks:
      - geocontrol-network
    volumes:
      - ./bd_data:/var/opt/mssql/data
      - geocontrol_sql_data:/var/opt/mssql
      - /etc/localtime:/etc/localtime:ro
volumes:
    geocontrol_sql_data:

networks:
  geocontrol-network:
    driver: bridge
